name: CI

on:
  push:
    branches: [develop]
  merge:
    branches: [develop]

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Setup Node.js
      uses: actions/setup-node@master
      with:
        node-version: 16.x
    - name: Install dependencies
      run: npx ci
    - name: Cache node modules
      uses: actions/cache@master
      env:
        cache-name: cache-node-modules
      with:
        path: ./node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

  lint:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Setup Node.js
      uses: actions/setup-node@master
      with:
        node-version: 16.x
    - name: Cache node modules
      uses: actions/cache@master
      env:
        cache-name: cache-node-modules
      with:
        path: ./node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Lint
      run: npm run lint

  build:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Setup Node.js
      uses: actions/setup-node@master
      with:
        node-version: 16.x
    - name: Cache node modules
      uses: actions/cache@master
      env:
        cache-name: cache-node-modules
      with:
        path: ./node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Build
      run: npm run build
